"use strict";

// Central catalog shared by the local SQLite and Turso adapters.
const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    email_verified_at INTEGER,
    auth_version INTEGER NOT NULL DEFAULT 1,
    suspended_at INTEGER
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    csrf_token TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    auth_version INTEGER NOT NULL DEFAULT 1
  )`,
  "CREATE INDEX IF NOT EXISTS sessions_user_id ON sessions(user_id)",
  "CREATE INDEX IF NOT EXISTS sessions_expires_at ON sessions(expires_at)",
  `CREATE TABLE IF NOT EXISTS signup_verifications (
    challenge_id TEXT PRIMARY KEY,
    browser_token_hash TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL,
    purpose TEXT NOT NULL DEFAULT 'signup' CHECK(purpose IN ('signup','login')),
    email TEXT NOT NULL COLLATE NOCASE,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    code_digest TEXT NOT NULL,
    generation INTEGER NOT NULL CHECK(generation >= 1),
    attempts_used INTEGER NOT NULL DEFAULT 0 CHECK(attempts_used >= 0),
    send_count INTEGER NOT NULL DEFAULT 0 CHECK(send_count >= 0),
    last_sent_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    hard_expires_at INTEGER NOT NULL,
    delivery_state TEXT NOT NULL,
    consumed_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    CHECK(expires_at <= hard_expires_at)
  )`,
  "CREATE INDEX IF NOT EXISTS signup_verifications_user_id_idx ON signup_verifications(user_id)",
  "CREATE INDEX IF NOT EXISTS signup_verifications_email ON signup_verifications(email,consumed_at,created_at)",
  "CREATE INDEX IF NOT EXISTS signup_verifications_expiry ON signup_verifications(hard_expires_at,consumed_at)",
  `CREATE TABLE IF NOT EXISTS email_verification_sends (
    send_id TEXT PRIMARY KEY,
    email_hash TEXT NOT NULL,
    challenge_id TEXT NOT NULL,
    generation INTEGER NOT NULL CHECK(generation >= 1),
    sent_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS email_verification_sends_email_time ON email_verification_sends(email_hash,sent_at)",
  "CREATE INDEX IF NOT EXISTS email_verification_sends_time ON email_verification_sends(sent_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS email_verification_sends_challenge_generation ON email_verification_sends(challenge_id,generation)",
  `CREATE TABLE IF NOT EXISTS account_action_requests (
    request_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose TEXT NOT NULL CHECK(purpose IN ('password_reset','account_delete')),
    token_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    delivery_state TEXT NOT NULL,
    consumed_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE(user_id,purpose)
  )`,
  "CREATE INDEX IF NOT EXISTS account_action_requests_expiry ON account_action_requests(expires_at,consumed_at)",
  `CREATE TABLE IF NOT EXISTS account_action_deliveries (
    request_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose TEXT NOT NULL CHECK(purpose IN ('password_reset','account_delete')),
    token_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS account_action_deliveries_user_purpose ON account_action_deliveries(user_id,purpose)",
  "CREATE INDEX IF NOT EXISTS account_action_deliveries_expiry ON account_action_deliveries(expires_at)",
  `CREATE TABLE IF NOT EXISTS account_action_sends (
    send_id TEXT PRIMARY KEY,
    email_hash TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK(purpose IN ('password_reset','account_delete')),
    sent_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS account_action_sends_email_time ON account_action_sends(email_hash,purpose,sent_at)",
  "CREATE INDEX IF NOT EXISTS account_action_sends_time ON account_action_sends(sent_at)",
  `CREATE TABLE IF NOT EXISTS plans (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    plan_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS community_weekly_plans (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 80),
    description TEXT NOT NULL DEFAULT '' CHECK(length(description) <= 240),
    plan_json TEXT NOT NULL,
    is_published INTEGER NOT NULL DEFAULT 1 CHECK(is_published IN (0,1)),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS community_weekly_plans_public_updated ON community_weekly_plans(is_published,updated_at DESC,id DESC)",
  `CREATE TABLE IF NOT EXISTS monthly_plans (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    plan_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS preferences (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    preferences_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ratings (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exercise_id TEXT NOT NULL,
    comfort INTEGER NOT NULL CHECK(comfort BETWEEN 1 AND 5),
    pump INTEGER NOT NULL CHECK(pump BETWEEN 1 AND 5),
    enjoyment INTEGER NOT NULL CHECK(enjoyment BETWEEN 1 AND 5),
    stability INTEGER NOT NULL CHECK(stability BETWEEN 1 AND 5),
    setup INTEGER NOT NULL CHECK(setup BETWEEN 1 AND 5),
    overall INTEGER NOT NULL CHECK(overall BETWEEN 1 AND 5),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY(user_id,exercise_id)
  )`,
  "CREATE INDEX IF NOT EXISTS ratings_exercise_id ON ratings(exercise_id)",
  `CREATE TABLE IF NOT EXISTS paddle_purchases (
    transaction_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    price_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    customer_id TEXT,
    paddle_status TEXT NOT NULL,
    completed_at INTEGER,
    access_revoked_at INTEGER,
    revocation_reason TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS paddle_purchases_user_id ON paddle_purchases(user_id)",
  `CREATE TABLE IF NOT EXISTS paddle_checkout_claims (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    price_id TEXT NOT NULL,
    claim_id TEXT NOT NULL,
    transaction_id TEXT,
    expires_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS paddle_checkout_claims_claim_id ON paddle_checkout_claims(claim_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS paddle_checkout_claims_transaction_id ON paddle_checkout_claims(transaction_id)",
  `CREATE TABLE IF NOT EXISTS discovery_trials (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    started_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    CHECK(expires_at > started_at)
  )`,
  `CREATE TABLE IF NOT EXISTS paddle_adjustments (
    adjustment_id TEXT PRIMARY KEY,
    transaction_id TEXT NOT NULL REFERENCES paddle_purchases(transaction_id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    type TEXT,
    status TEXT NOT NULL,
    occurred_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS paddle_adjustments_transaction_id ON paddle_adjustments(transaction_id)",
  `CREATE TABLE IF NOT EXISTS paddle_webhook_events (
    event_id TEXT PRIMARY KEY,
    notification_id TEXT,
    event_type TEXT NOT NULL,
    occurred_at INTEGER NOT NULL,
    processed_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS support_tickets (
    id TEXT PRIMARY KEY,
    reference TEXT NOT NULL UNIQUE,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL COLLATE NOCASE,
    category TEXT NOT NULL CHECK(category IN ('account','password','payment','privacy','exercise','other')),
    subject TEXT NOT NULL,
    reference_id TEXT,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','open','waiting','resolved')),
    admin_note TEXT,
    last_response_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS support_tickets_status_updated ON support_tickets(status,updated_at DESC)",
  `CREATE TABLE IF NOT EXISTS support_request_events (
    id TEXT PRIMARY KEY,
    ip_hash TEXT NOT NULL,
    email_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS support_request_events_ip_time ON support_request_events(ip_hash,created_at)",
  "CREATE INDEX IF NOT EXISTS support_request_events_email_time ON support_request_events(email_hash,created_at)",
  "CREATE INDEX IF NOT EXISTS support_request_events_time ON support_request_events(created_at)",
  `CREATE TABLE IF NOT EXISTS admin_principal (
    slot TEXT PRIMARY KEY CHECK(slot='primary'),
    user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    configured_email TEXT NOT NULL COLLATE NOCASE,
    bound_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS admin_elevations (
    session_token_hash TEXT PRIMARY KEY REFERENCES sessions(token_hash) ON DELETE CASCADE,
    expires_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS admin_elevations_expiry ON admin_elevations(expires_at)",
  `CREATE TABLE IF NOT EXISTS admin_audit_events (
    id TEXT PRIMARY KEY,
    actor_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    target_user_id TEXT,
    action TEXT NOT NULL,
    reason TEXT NOT NULL,
    result TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS admin_audit_created ON admin_audit_events(created_at DESC)",
  "CREATE INDEX IF NOT EXISTS admin_audit_actor ON admin_audit_events(actor_user_id,created_at DESC)",
  `CREATE TRIGGER IF NOT EXISTS admin_principal_secure_claim
    AFTER INSERT ON admin_principal
    BEGIN
      UPDATE users SET auth_version=auth_version+1 WHERE id=NEW.user_id;
      DELETE FROM sessions WHERE user_id=NEW.user_id;
      DELETE FROM account_action_requests WHERE user_id=NEW.user_id;
      DELETE FROM account_action_deliveries WHERE user_id=NEW.user_id;
      INSERT INTO admin_audit_events(id,actor_user_id,target_user_id,action,reason,result,created_at)
      VALUES(lower(hex(randomblob(16))),NEW.user_id,NEW.user_id,'admin-bound','Primary administrator activated','success',NEW.bound_at);
    END`
];

const SQL = {
  ping:"SELECT 1 AS ok",
  userByEmail:"SELECT * FROM users WHERE email = ?",
  userById:"SELECT id,name,email,created_at,email_verified_at,auth_version,suspended_at FROM users WHERE id = ?",
  accountCredentialsById:"SELECT id,email,password_hash,password_salt,auth_version,suspended_at FROM users WHERE id = ?",
  insertUser:"INSERT INTO users(id,name,email,password_hash,password_salt,created_at,email_verified_at) VALUES(?,?,?,?,?,?,?)",
  insertSession:"INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at,created_at,auth_version) SELECT ?,id,?,?,?,auth_version FROM users WHERE id=? AND auth_version=? AND suspended_at IS NULL RETURNING token_hash",
  session:"SELECT s.token_hash,s.csrf_token,s.expires_at,u.id,u.name,u.email,u.created_at,u.email_verified_at,u.auth_version,u.suspended_at FROM sessions s JOIN users u ON u.id=s.user_id AND u.auth_version=s.auth_version AND u.suspended_at IS NULL WHERE s.token_hash=? AND s.expires_at>?",
  deleteSession:"DELETE FROM sessions WHERE token_hash=?",
  deleteExpired:"DELETE FROM sessions WHERE expires_at<=?",
  verificationByTokenHash:"SELECT challenge_id,browser_token_hash,user_id,purpose,email,name,password_hash,password_salt,code_digest,generation,attempts_used,send_count,last_sent_at,expires_at,hard_expires_at,delivery_state,consumed_at,created_at,updated_at FROM signup_verifications WHERE browser_token_hash=?",
  verificationByChallenge:"SELECT challenge_id,browser_token_hash,user_id,purpose,email,name,password_hash,password_salt,code_digest,generation,attempts_used,send_count,last_sent_at,expires_at,hard_expires_at,delivery_state,consumed_at,created_at,updated_at FROM signup_verifications WHERE challenge_id=?",
  insertVerification:"INSERT INTO signup_verifications(challenge_id,browser_token_hash,user_id,purpose,email,name,password_hash,password_salt,code_digest,generation,attempts_used,send_count,last_sent_at,expires_at,hard_expires_at,delivery_state,consumed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL,?,?)",
  rotateVerification:"UPDATE signup_verifications SET code_digest=?,generation=generation+1,attempts_used=0,send_count=send_count+1,last_sent_at=?,expires_at=?,delivery_state=?,updated_at=? WHERE challenge_id=? AND generation=? AND consumed_at IS NULL RETURNING challenge_id,browser_token_hash,user_id,purpose,email,name,password_hash,password_salt,code_digest,generation,attempts_used,send_count,last_sent_at,expires_at,hard_expires_at,delivery_state,consumed_at,created_at,updated_at",
  markVerificationDelivery:"UPDATE signup_verifications SET delivery_state=?,updated_at=? WHERE challenge_id=? AND generation=? AND consumed_at IS NULL RETURNING challenge_id",
  claimVerificationAttempt:"UPDATE signup_verifications SET attempts_used=attempts_used+1,updated_at=? WHERE challenge_id=? AND generation=? AND consumed_at IS NULL AND expires_at>? AND hard_expires_at>? AND attempts_used<? RETURNING challenge_id,browser_token_hash,user_id,purpose,email,name,password_hash,password_salt,code_digest,generation,attempts_used,send_count,last_sent_at,expires_at,hard_expires_at,delivery_state,consumed_at,created_at,updated_at",
  consumeVerification:"UPDATE signup_verifications SET code_digest='',password_hash='',password_salt='',delivery_state='consumed',consumed_at=?,updated_at=? WHERE challenge_id=? AND generation=? AND consumed_at IS NULL RETURNING challenge_id,browser_token_hash,user_id,purpose,email,name,password_hash,password_salt,code_digest,generation,attempts_used,send_count,last_sent_at,expires_at,hard_expires_at,delivery_state,consumed_at,created_at,updated_at",
  completeSignupInsert:"INSERT INTO users(id,name,email,password_hash,password_salt,created_at,email_verified_at) SELECT user_id,name,email,password_hash,password_salt,?,? FROM signup_verifications WHERE challenge_id=? AND generation=? AND purpose='signup' AND consumed_at IS NULL AND expires_at>? AND hard_expires_at>? RETURNING id,name,email,created_at,email_verified_at,auth_version,suspended_at",
  completeSignupConsume:"UPDATE signup_verifications SET code_digest='',password_hash='',password_salt='',delivery_state='consumed',consumed_at=?,updated_at=? WHERE changes()=1 AND challenge_id=? AND generation=? AND purpose='signup' AND consumed_at IS NULL AND expires_at>? AND hard_expires_at>? RETURNING challenge_id",
  completeSignupSession:"INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at,created_at,auth_version) SELECT ?,v.user_id,?,?,?,u.auth_version FROM signup_verifications v JOIN users u ON u.id=v.user_id WHERE changes()=1 AND v.challenge_id=? AND v.generation=? AND v.purpose='signup' AND v.consumed_at=? RETURNING token_hash",
  completeLoginVerifyUser:"UPDATE users SET email_verified_at=? WHERE email_verified_at IS NULL AND suspended_at IS NULL AND id=(SELECT user_id FROM signup_verifications WHERE challenge_id=? AND generation=? AND purpose='login' AND consumed_at IS NULL AND expires_at>? AND hard_expires_at>?) RETURNING id,name,email,created_at,email_verified_at,auth_version,suspended_at",
  completeLoginConsume:"UPDATE signup_verifications SET code_digest='',password_hash='',password_salt='',delivery_state='consumed',consumed_at=?,updated_at=? WHERE changes()=1 AND challenge_id=? AND generation=? AND purpose='login' AND consumed_at IS NULL AND expires_at>? AND hard_expires_at>? RETURNING challenge_id",
  completeLoginSession:"INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at,created_at,auth_version) SELECT ?,v.user_id,?,?,?,u.auth_version FROM signup_verifications v JOIN users u ON u.id=v.user_id AND u.suspended_at IS NULL WHERE changes()=1 AND v.challenge_id=? AND v.generation=? AND v.purpose='login' AND v.consumed_at=? RETURNING token_hash",
  completeLoginDeleteOldSessions:"DELETE FROM sessions WHERE changes()=1 AND user_id=(SELECT user_id FROM signup_verifications WHERE challenge_id=? AND generation=? AND purpose='login' AND consumed_at=?) AND token_hash<>? RETURNING token_hash",
  countVerificationSends:"SELECT COUNT(*) AS send_count FROM email_verification_sends WHERE email_hash=? AND sent_at>=?",
  recordVerificationSend:"INSERT INTO email_verification_sends(send_id,email_hash,challenge_id,generation,sent_at) VALUES(?,?,?,?,?)",
  claimVerificationSend:"INSERT OR IGNORE INTO email_verification_sends(send_id,email_hash,challenge_id,generation,sent_at) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM email_verification_sends WHERE email_hash=? AND sent_at>=?)<? RETURNING send_id",
  verificationSendByChallengeGeneration:"SELECT send_id,email_hash,challenge_id,generation,sent_at FROM email_verification_sends WHERE challenge_id=? AND generation=?",
  deleteOldVerifications:"DELETE FROM signup_verifications WHERE hard_expires_at<=? OR (consumed_at IS NOT NULL AND consumed_at<=?)",
  deleteOldVerificationSends:"DELETE FROM email_verification_sends WHERE sent_at<?",
  accountActionByTokenHash:"SELECT a.request_id,a.user_id,a.purpose,a.token_hash,a.expires_at,a.delivery_state,a.consumed_at,a.created_at,a.updated_at,u.email,u.name FROM account_action_requests a JOIN users u ON u.id=a.user_id WHERE a.token_hash=?",
  accountActionForUser:"SELECT request_id,user_id,purpose,token_hash,expires_at,delivery_state,consumed_at,created_at,updated_at FROM account_action_requests WHERE user_id=? AND purpose=?",
  upsertAccountAction:"INSERT INTO account_action_requests(request_id,user_id,purpose,token_hash,expires_at,delivery_state,consumed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,NULL,?,?) ON CONFLICT(user_id,purpose) DO UPDATE SET request_id=excluded.request_id,token_hash=excluded.token_hash,expires_at=excluded.expires_at,delivery_state=excluded.delivery_state,consumed_at=NULL,created_at=excluded.created_at,updated_at=excluded.updated_at RETURNING request_id,user_id,purpose,token_hash,expires_at,delivery_state,consumed_at,created_at,updated_at",
  markAccountActionDelivery:"UPDATE account_action_requests SET delivery_state=?,updated_at=? WHERE request_id=? AND token_hash=? AND consumed_at IS NULL RETURNING request_id",
  stageAccountAction:"INSERT INTO account_action_deliveries(request_id,user_id,purpose,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,purpose) DO UPDATE SET request_id=excluded.request_id,token_hash=excluded.token_hash,expires_at=excluded.expires_at,created_at=excluded.created_at RETURNING request_id,user_id,purpose,token_hash,expires_at,created_at",
  activateAccountAction:"INSERT INTO account_action_requests(request_id,user_id,purpose,token_hash,expires_at,delivery_state,consumed_at,created_at,updated_at) SELECT request_id,user_id,purpose,token_hash,expires_at,'sent',NULL,created_at,? FROM account_action_deliveries WHERE request_id=? AND token_hash=? AND expires_at>? ON CONFLICT(user_id,purpose) DO UPDATE SET request_id=excluded.request_id,token_hash=excluded.token_hash,expires_at=excluded.expires_at,delivery_state='sent',consumed_at=NULL,created_at=excluded.created_at,updated_at=excluded.updated_at WHERE account_action_requests.created_at<=excluded.created_at RETURNING request_id,user_id,purpose,token_hash,expires_at,delivery_state,consumed_at,created_at,updated_at",
  discardStagedAccountAction:"DELETE FROM account_action_deliveries WHERE request_id=? AND token_hash=? RETURNING request_id",
  claimAccountActionSend:"INSERT OR IGNORE INTO account_action_sends(send_id,email_hash,purpose,sent_at) SELECT ?,?,?,? WHERE (SELECT COUNT(*) FROM account_action_sends WHERE email_hash=? AND purpose=? AND sent_at>=?)<? RETURNING send_id",
  countAccountActionSends:"SELECT COUNT(*) AS send_count FROM account_action_sends WHERE email_hash=? AND purpose=? AND sent_at>=?",
  deleteOldAccountActions:"DELETE FROM account_action_requests WHERE expires_at<=? OR (consumed_at IS NOT NULL AND consumed_at<=?)",
  deleteOldStagedAccountActions:"DELETE FROM account_action_deliveries WHERE expires_at<=?",
  deleteOldAccountActionSends:"DELETE FROM account_action_sends WHERE sent_at<?",
  activeAccountDeletion:"SELECT request_id,expires_at FROM account_action_requests WHERE user_id=? AND purpose='account_delete' AND delivery_state='sent' AND consumed_at IS NULL AND expires_at>?",
  activeCheckoutCreationForUser:"SELECT user_id,price_id,claim_id,transaction_id,expires_at,created_at,updated_at FROM paddle_checkout_claims WHERE user_id=? AND expires_at>?",
  cancelAccountDeletion:"DELETE FROM account_action_requests WHERE user_id=? AND purpose='account_delete' AND delivery_state='sent' AND consumed_at IS NULL RETURNING request_id",
  cancelStagedAccountDeletions:"DELETE FROM account_action_deliveries WHERE user_id=? AND purpose='account_delete' RETURNING request_id",
  cancelStagedAccountDeletionsIfAudit:"DELETE FROM account_action_deliveries WHERE user_id=? AND purpose='account_delete' AND EXISTS(SELECT 1 FROM admin_audit_events WHERE id=?) RETURNING request_id",
  completePasswordResetUser:"UPDATE users SET password_hash=?,password_salt=?,email_verified_at=COALESCE(email_verified_at,?),auth_version=auth_version+1 WHERE id=(SELECT user_id FROM account_action_requests WHERE token_hash=? AND purpose='password_reset' AND delivery_state='sent' AND consumed_at IS NULL AND expires_at>?) RETURNING id,name,email,created_at,email_verified_at,auth_version,suspended_at",
  completePasswordResetConsume:"UPDATE account_action_requests SET consumed_at=?,delivery_state='consumed',updated_at=? WHERE changes()=1 AND token_hash=? AND purpose='password_reset' AND delivery_state='sent' AND consumed_at IS NULL AND expires_at>? RETURNING user_id",
  completePasswordResetDeleteSessions:"DELETE FROM sessions WHERE user_id=(SELECT user_id FROM account_action_requests WHERE token_hash=? AND purpose='password_reset' AND consumed_at=?) RETURNING token_hash",
  completePasswordResetDeleteStagedActions:"DELETE FROM account_action_deliveries WHERE user_id=(SELECT user_id FROM account_action_requests WHERE token_hash=? AND purpose='password_reset' AND consumed_at=?) RETURNING request_id",
  completePasswordResetDeleteActions:"DELETE FROM account_action_requests WHERE user_id=(SELECT user_id FROM account_action_requests WHERE token_hash=? AND purpose='password_reset' AND consumed_at=?) RETURNING request_id",
  pendingPurchasesForUser:"SELECT COUNT(*) AS pending_count FROM paddle_purchases WHERE user_id=? AND paddle_status<>'canceled' AND completed_at IS NULL AND access_revoked_at IS NULL",
  unsettledPurchasesForUser:"SELECT transaction_id,user_id,price_id,product_id,customer_id,paddle_status,completed_at,access_revoked_at,revocation_reason,created_at,updated_at FROM paddle_purchases WHERE user_id=? AND paddle_status<>'canceled' AND completed_at IS NULL AND access_revoked_at IS NULL ORDER BY created_at",
  deleteUserWithAction:"DELETE FROM users WHERE id=(SELECT user_id FROM account_action_requests WHERE token_hash=? AND purpose='account_delete' AND delivery_state='sent' AND consumed_at IS NULL AND expires_at>?) AND NOT EXISTS (SELECT 1 FROM admin_principal ap WHERE ap.user_id=users.id) AND NOT EXISTS (SELECT 1 FROM paddle_purchases p WHERE p.user_id=users.id AND p.paddle_status<>'canceled' AND p.completed_at IS NULL AND p.access_revoked_at IS NULL) AND NOT EXISTS (SELECT 1 FROM paddle_checkout_claims c WHERE c.user_id=users.id AND c.expires_at>?) RETURNING id,email",
  deleteVerificationSendsForDeletedUser:"DELETE FROM email_verification_sends WHERE challenge_id IN (SELECT challenge_id FROM signup_verifications WHERE user_id=? OR email=?) AND NOT EXISTS (SELECT 1 FROM users WHERE id=?)",
  deleteVerificationsForDeletedUser:"DELETE FROM signup_verifications WHERE (user_id=? OR email=?) AND NOT EXISTS (SELECT 1 FROM users WHERE id=?)",
  deleteActionSendsForDeletedUser:"DELETE FROM account_action_sends WHERE email_hash=? AND NOT EXISTS (SELECT 1 FROM users WHERE id=?)",
  deleteCommunityPlanForDeletedUser:"DELETE FROM community_weekly_plans WHERE user_id=? AND NOT EXISTS (SELECT 1 FROM users WHERE id=?) RETURNING id",
  deleteCheckoutClaimsForDeletedUser:"DELETE FROM paddle_checkout_claims WHERE user_id=? AND NOT EXISTS (SELECT 1 FROM users WHERE id=?) RETURNING claim_id",
  plan:"SELECT plan_json,updated_at FROM plans WHERE user_id=?",
  upsertPlan:"INSERT INTO plans(user_id,plan_json,updated_at) SELECT u.id,?,? FROM users u WHERE u.id=? AND u.suspended_at IS NULL AND (?=0 OR EXISTS(SELECT 1 FROM plans current_plan WHERE current_plan.user_id=u.id AND current_plan.updated_at=?)) ON CONFLICT(user_id) DO UPDATE SET plan_json=excluded.plan_json,updated_at=MAX(plans.updated_at+1,excluded.updated_at) WHERE ?<>0 AND plans.updated_at=? RETURNING plan_json,updated_at",
  communityWeeklyPlans:"SELECT c.id,c.title,c.description,c.plan_json,c.created_at,c.updated_at,u.name AS author_name FROM community_weekly_plans c JOIN users u ON u.id=c.user_id AND u.suspended_at IS NULL WHERE c.is_published=1 ORDER BY c.updated_at DESC,c.id DESC LIMIT ? OFFSET ?",
  communityWeeklyPlan:"SELECT c.id,c.title,c.description,c.plan_json,c.created_at,c.updated_at,u.name AS author_name FROM community_weekly_plans c JOIN users u ON u.id=c.user_id AND u.suspended_at IS NULL WHERE c.id=? AND c.is_published=1",
  communityWeeklyPlansForUser:"SELECT c.id,c.title,c.description,c.plan_json,c.is_published,c.created_at,c.updated_at,u.name AS author_name FROM community_weekly_plans c JOIN users u ON u.id=c.user_id WHERE c.user_id=? ORDER BY c.updated_at DESC,c.id DESC",
  communityWeeklyPlanForOwner:"SELECT c.id,c.title,c.description,c.plan_json,c.is_published,c.created_at,c.updated_at,u.name AS author_name FROM community_weekly_plans c JOIN users u ON u.id=c.user_id WHERE c.id=? AND c.user_id=?",
  upsertCommunityWeeklyPlan:"INSERT INTO community_weekly_plans(id,user_id,title,description,plan_json,is_published,created_at,updated_at) SELECT ?,u.id,?,?,?,?,?,? FROM users u WHERE u.id=? AND u.suspended_at IS NULL ON CONFLICT(user_id) DO UPDATE SET title=excluded.title,description=excluded.description,plan_json=excluded.plan_json,is_published=excluded.is_published,updated_at=MAX(community_weekly_plans.updated_at+1,excluded.updated_at) RETURNING id,user_id,title,description,plan_json,is_published,created_at,updated_at",
  upsertCommunityWeeklyPlanFromPlan:"INSERT INTO community_weekly_plans(id,user_id,title,description,plan_json,is_published,created_at,updated_at) SELECT ?,u.id,?,?,p.plan_json,?,?,? FROM users u JOIN plans p ON p.user_id=u.id WHERE u.id=? AND u.suspended_at IS NULL AND p.updated_at=? AND p.plan_json=? ON CONFLICT(user_id) DO UPDATE SET title=excluded.title,description=excluded.description,plan_json=excluded.plan_json,is_published=excluded.is_published,updated_at=MAX(community_weekly_plans.updated_at+1,excluded.updated_at) RETURNING id,user_id,title,description,plan_json,is_published,created_at,updated_at",
  setCommunityWeeklyPlanPublished:"UPDATE community_weekly_plans SET is_published=?,updated_at=MAX(updated_at+1,?) WHERE id=? AND user_id=? RETURNING id,user_id,title,description,plan_json,is_published,created_at,updated_at",
  deleteCommunityWeeklyPlan:"DELETE FROM community_weekly_plans WHERE id=? AND user_id=? RETURNING id",
  applyCommunityWeeklyPlan:"INSERT INTO plans(user_id,plan_json,updated_at) SELECT target.id,?,MAX(?,COALESCE(current_plan.updated_at,0)+1) FROM community_weekly_plans c JOIN users author ON author.id=c.user_id AND author.suspended_at IS NULL JOIN users target ON target.id=? AND target.suspended_at IS NULL LEFT JOIN plans current_plan ON current_plan.user_id=target.id WHERE c.id=? AND c.is_published=1 AND c.updated_at=? AND c.plan_json=? AND COALESCE(current_plan.updated_at,0)=? ON CONFLICT(user_id) DO UPDATE SET plan_json=excluded.plan_json,updated_at=excluded.updated_at RETURNING plan_json,updated_at",
  monthlyPlan:"SELECT plan_json,updated_at FROM monthly_plans WHERE user_id=?",
  upsertMonthlyPlan:"INSERT INTO monthly_plans(user_id,plan_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET plan_json=excluded.plan_json,updated_at=excluded.updated_at",
  compareAndSwapMonthlyPlan:"INSERT INTO monthly_plans(user_id,plan_json,updated_at) SELECT ?,?,? WHERE COALESCE((SELECT updated_at FROM monthly_plans WHERE user_id=?),0)=? ON CONFLICT(user_id) DO UPDATE SET plan_json=excluded.plan_json,updated_at=excluded.updated_at WHERE monthly_plans.updated_at=? RETURNING plan_json,updated_at",
  preferences:"SELECT preferences_json,updated_at FROM preferences WHERE user_id=?",
  upsertPreferences:"INSERT INTO preferences(user_id,preferences_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET preferences_json=excluded.preferences_json,updated_at=excluded.updated_at",
  ratingsForUser:"SELECT exercise_id,comfort,pump,enjoyment,stability,setup,overall,updated_at FROM ratings WHERE user_id=?",
  ratingAggregates:"SELECT exercise_id,COUNT(*) AS rating_count,AVG(comfort) AS comfort,AVG(pump) AS pump,AVG(enjoyment) AS enjoyment,AVG(stability) AS stability,AVG(setup) AS setup,AVG(overall) AS overall FROM ratings GROUP BY exercise_id",
  ratingAggregate:"SELECT exercise_id,COUNT(*) AS rating_count,AVG(comfort) AS comfort,AVG(pump) AS pump,AVG(enjoyment) AS enjoyment,AVG(stability) AS stability,AVG(setup) AS setup,AVG(overall) AS overall FROM ratings WHERE exercise_id=? GROUP BY exercise_id",
  upsertRating:"INSERT INTO ratings(user_id,exercise_id,comfort,pump,enjoyment,stability,setup,overall,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,exercise_id) DO UPDATE SET comfort=excluded.comfort,pump=excluded.pump,enjoyment=excluded.enjoyment,stability=excluded.stability,setup=excluded.setup,overall=excluded.overall,updated_at=excluded.updated_at",
  insertPendingPurchase:"INSERT INTO paddle_purchases(transaction_id,user_id,price_id,product_id,customer_id,paddle_status,completed_at,access_revoked_at,revocation_reason,created_at,updated_at) SELECT ?,u.id,?,?,NULL,?,NULL,NULL,NULL,?,? FROM users u WHERE u.id=? AND u.suspended_at IS NULL AND NOT EXISTS (SELECT 1 FROM account_action_requests a WHERE a.user_id=u.id AND a.purpose='account_delete' AND a.delivery_state='sent' AND a.consumed_at IS NULL AND a.expires_at>?) AND NOT EXISTS (SELECT 1 FROM paddle_purchases p WHERE p.user_id=u.id AND p.paddle_status<>'canceled' AND p.completed_at IS NULL AND p.access_revoked_at IS NULL) RETURNING transaction_id,user_id,price_id,product_id,customer_id,paddle_status,completed_at,access_revoked_at,revocation_reason,created_at,updated_at",
  checkoutCreationForUser:"SELECT user_id,price_id,claim_id,transaction_id,expires_at,created_at,updated_at FROM paddle_checkout_claims WHERE user_id=?",
  claimCheckoutCreation:"INSERT INTO paddle_checkout_claims(user_id,price_id,claim_id,transaction_id,expires_at,created_at,updated_at) SELECT u.id,?,?,NULL,?,?,? FROM users u WHERE u.id=? AND u.suspended_at IS NULL AND NOT EXISTS (SELECT 1 FROM account_action_requests a WHERE a.user_id=u.id AND a.purpose='account_delete' AND a.delivery_state='sent' AND a.consumed_at IS NULL AND a.expires_at>?) ON CONFLICT(user_id) DO UPDATE SET price_id=excluded.price_id,claim_id=excluded.claim_id,transaction_id=NULL,expires_at=excluded.expires_at,created_at=excluded.created_at,updated_at=excluded.updated_at WHERE paddle_checkout_claims.expires_at<=? AND paddle_checkout_claims.transaction_id IS NULL RETURNING user_id,price_id,claim_id,transaction_id,expires_at,created_at,updated_at",
  recordCheckoutCreationTransaction:"UPDATE paddle_checkout_claims SET transaction_id=?,updated_at=MAX(updated_at,?) WHERE user_id=? AND claim_id=? AND (transaction_id IS NULL OR transaction_id=?) RETURNING user_id,price_id,claim_id,transaction_id,expires_at,created_at,updated_at",
  extendCheckoutCreation:"UPDATE paddle_checkout_claims SET expires_at=MAX(expires_at,?),updated_at=MAX(updated_at,?) WHERE user_id=? AND claim_id=? RETURNING user_id,price_id,claim_id,transaction_id,expires_at,created_at,updated_at",
  releaseCheckoutCreation:"DELETE FROM paddle_checkout_claims WHERE user_id=? AND claim_id=? AND transaction_id IS ? RETURNING claim_id",
  purchaseByTransaction:"SELECT transaction_id,user_id,price_id,product_id,customer_id,paddle_status,completed_at,access_revoked_at,revocation_reason,created_at,updated_at FROM paddle_purchases WHERE transaction_id=?",
  pendingPurchaseForUser:"SELECT transaction_id,user_id,price_id,product_id,customer_id,paddle_status,completed_at,access_revoked_at,revocation_reason,created_at,updated_at FROM paddle_purchases WHERE user_id=? AND price_id=? AND paddle_status IN ('draft','ready') AND completed_at IS NULL AND access_revoked_at IS NULL ORDER BY created_at DESC LIMIT 1",
  completePurchase:"UPDATE paddle_purchases SET customer_id=COALESCE(customer_id,?),paddle_status='completed',completed_at=COALESCE(completed_at,?),updated_at=MAX(updated_at,?) WHERE transaction_id=?",
  updatePurchaseStatus:"UPDATE paddle_purchases SET paddle_status=?,updated_at=? WHERE transaction_id=? AND paddle_status<>'completed' AND updated_at<=?",
  upsertAdjustment:"INSERT INTO paddle_adjustments(adjustment_id,transaction_id,action,type,status,occurred_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(adjustment_id) DO UPDATE SET action=excluded.action,type=excluded.type,status=excluded.status,occurred_at=excluded.occurred_at,updated_at=excluded.updated_at WHERE excluded.occurred_at>=paddle_adjustments.occurred_at RETURNING adjustment_id",
  revokePurchase:"UPDATE paddle_purchases SET access_revoked_at=?,revocation_reason=?,updated_at=MAX(updated_at,?) WHERE transaction_id=? AND access_revoked_at IS NULL",
  hasDiscoveryAccess:"SELECT 1 AS active FROM paddle_purchases WHERE user_id=? AND (? IS NULL OR price_id=?) AND paddle_status='completed' AND completed_at IS NOT NULL AND access_revoked_at IS NULL LIMIT 1",
  discoveryTrial:"SELECT user_id,started_at,expires_at FROM discovery_trials WHERE user_id=?",
  activeDiscoveryTrial:"SELECT user_id,started_at,expires_at FROM discovery_trials WHERE user_id=? AND expires_at>?",
  startDiscoveryTrial:"INSERT OR IGNORE INTO discovery_trials(user_id,started_at,expires_at) SELECT id,?,? FROM users WHERE id=? AND suspended_at IS NULL RETURNING user_id,started_at,expires_at",
  discoveryAccessSummary:"SELECT COUNT(*) AS purchase_count,COALESCE(SUM(CASE WHEN paddle_status='completed' AND completed_at IS NOT NULL AND access_revoked_at IS NULL THEN 1 ELSE 0 END),0) AS active_purchase_count,COALESCE(SUM(CASE WHEN paddle_status<>'canceled' AND completed_at IS NULL AND access_revoked_at IS NULL THEN 1 ELSE 0 END),0) AS pending_purchase_count,MAX(CASE WHEN paddle_status='completed' AND access_revoked_at IS NULL THEN completed_at ELSE NULL END) AS latest_active_purchase_at,MAX(completed_at) AS latest_completed_at,MAX(access_revoked_at) AS latest_revoked_at FROM paddle_purchases WHERE user_id=? AND (? IS NULL OR price_id=?)",
  adjustmentById:"SELECT adjustment_id,transaction_id,action,type,status,occurred_at,updated_at FROM paddle_adjustments WHERE adjustment_id=?",
  webhookEvent:"SELECT event_id,notification_id,event_type,occurred_at,processed_at FROM paddle_webhook_events WHERE event_id=?",
  recordWebhookEvent:"INSERT INTO paddle_webhook_events(event_id,notification_id,event_type,occurred_at,processed_at) VALUES(?,?,?,?,?) ON CONFLICT(event_id) DO NOTHING RETURNING event_id",
  adminOverview:"SELECT (SELECT COUNT(*) FROM users) AS total_users,(SELECT COUNT(*) FROM users WHERE email_verified_at IS NOT NULL) AS verified_users,(SELECT COUNT(*) FROM users WHERE suspended_at IS NOT NULL) AS suspended_users,(SELECT COUNT(*) FROM sessions s JOIN users u ON u.id=s.user_id AND u.auth_version=s.auth_version WHERE s.expires_at>? AND u.suspended_at IS NULL) AS active_sessions,(SELECT COUNT(DISTINCT user_id) FROM paddle_purchases WHERE paddle_status='completed' AND completed_at IS NOT NULL AND access_revoked_at IS NULL) AS discovery_users,(SELECT COUNT(*) FROM paddle_purchases WHERE paddle_status<>'canceled' AND completed_at IS NULL AND access_revoked_at IS NULL) AS pending_payments,(SELECT COUNT(*) FROM account_action_requests WHERE purpose='account_delete' AND delivery_state='sent' AND consumed_at IS NULL AND expires_at>?) AS pending_deletions,(SELECT COUNT(*) FROM support_tickets WHERE status<>'resolved') AS open_support",
  adminUserById:"SELECT u.id,u.name,u.email,u.created_at,u.email_verified_at,u.auth_version,u.suspended_at,p.plan_json,(SELECT COUNT(*) FROM sessions s WHERE s.user_id=u.id AND s.auth_version=u.auth_version AND s.expires_at>?) AS active_session_count,(SELECT COUNT(*) FROM ratings r WHERE r.user_id=u.id) AS rating_count,(SELECT COUNT(*) FROM paddle_purchases pp WHERE pp.user_id=u.id) AS purchase_count,(SELECT COUNT(*) FROM paddle_purchases pp WHERE pp.user_id=u.id AND pp.paddle_status='completed' AND pp.completed_at IS NOT NULL AND pp.access_revoked_at IS NULL) AS active_purchase_count,(SELECT COUNT(*) FROM paddle_purchases pp WHERE pp.user_id=u.id AND pp.paddle_status<>'canceled' AND pp.completed_at IS NULL AND pp.access_revoked_at IS NULL) AS pending_purchase_count,(SELECT MAX(pp.updated_at) FROM paddle_purchases pp WHERE pp.user_id=u.id) AS latest_purchase_at,(SELECT pp.transaction_id FROM paddle_purchases pp WHERE pp.user_id=u.id ORDER BY pp.updated_at DESC,pp.transaction_id DESC LIMIT 1) AS transaction_id,(SELECT pp.paddle_status FROM paddle_purchases pp WHERE pp.user_id=u.id ORDER BY pp.updated_at DESC,pp.transaction_id DESC LIMIT 1) AS transaction_status,(SELECT request_id FROM account_action_requests a WHERE a.user_id=u.id AND a.purpose='account_delete' AND a.delivery_state='sent' AND a.consumed_at IS NULL AND a.expires_at>? LIMIT 1) AS deletion_request_id,(SELECT expires_at FROM account_action_requests a WHERE a.user_id=u.id AND a.purpose='account_delete' AND a.delivery_state='sent' AND a.consumed_at IS NULL AND a.expires_at>? LIMIT 1) AS deletion_expires_at FROM users u LEFT JOIN plans p ON p.user_id=u.id WHERE u.id=?",
  adminUsers:"SELECT u.id,u.name,u.email,u.created_at,u.email_verified_at,u.suspended_at,(SELECT COUNT(*) FROM sessions s WHERE s.user_id=u.id AND s.auth_version=u.auth_version AND s.expires_at>?) AS active_session_count,(SELECT COUNT(*) FROM paddle_purchases pp WHERE pp.user_id=u.id) AS purchase_count,(SELECT COUNT(*) FROM paddle_purchases pp WHERE pp.user_id=u.id AND pp.paddle_status='completed' AND pp.completed_at IS NOT NULL AND pp.access_revoked_at IS NULL) AS active_purchase_count,(SELECT COUNT(*) FROM paddle_purchases pp WHERE pp.user_id=u.id AND pp.paddle_status<>'canceled' AND pp.completed_at IS NULL AND pp.access_revoked_at IS NULL) AS pending_purchase_count,(SELECT MAX(pp.updated_at) FROM paddle_purchases pp WHERE pp.user_id=u.id) AS latest_purchase_at,(SELECT pp.transaction_id FROM paddle_purchases pp WHERE pp.user_id=u.id ORDER BY pp.updated_at DESC,pp.transaction_id DESC LIMIT 1) AS transaction_id,(SELECT pp.paddle_status FROM paddle_purchases pp WHERE pp.user_id=u.id ORDER BY pp.updated_at DESC,pp.transaction_id DESC LIMIT 1) AS transaction_status,(SELECT expires_at FROM account_action_requests a WHERE a.user_id=u.id AND a.purpose='account_delete' AND a.delivery_state='sent' AND a.consumed_at IS NULL AND a.expires_at>? LIMIT 1) AS deletion_expires_at FROM users u WHERE (?='' OR lower(u.name) LIKE ? ESCAPE '\\' OR lower(u.email) LIKE ? ESCAPE '\\' OR lower(u.id) LIKE ? ESCAPE '\\' OR EXISTS (SELECT 1 FROM paddle_purchases pp WHERE pp.user_id=u.id AND lower(pp.transaction_id) LIKE ? ESCAPE '\\')) ORDER BY u.created_at DESC,u.id DESC LIMIT ? OFFSET ?",
  adminUserCount:"SELECT COUNT(*) AS total FROM users u WHERE (?='' OR lower(u.name) LIKE ? ESCAPE '\\' OR lower(u.email) LIKE ? ESCAPE '\\' OR lower(u.id) LIKE ? ESCAPE '\\' OR EXISTS (SELECT 1 FROM paddle_purchases pp WHERE pp.user_id=u.id AND lower(pp.transaction_id) LIKE ? ESCAPE '\\'))",
  adminPrincipal:"SELECT ap.slot,ap.user_id,ap.configured_email,ap.bound_at,u.name,u.email,u.email_verified_at,u.suspended_at,u.auth_version FROM admin_principal ap JOIN users u ON u.id=ap.user_id WHERE ap.slot='primary'",
  insertAdminPrincipal:"INSERT INTO admin_principal(slot,user_id,configured_email,bound_at) SELECT 'primary',id,?,? FROM users WHERE id=? AND email=? COLLATE NOCASE AND email_verified_at IS NOT NULL AND suspended_at IS NULL ON CONFLICT(slot) DO NOTHING RETURNING slot,user_id,configured_email,bound_at",
  upsertAdminElevation:"INSERT INTO admin_elevations(session_token_hash,expires_at,created_at) SELECT s.token_hash,?,? FROM sessions s JOIN admin_principal ap ON ap.user_id=s.user_id WHERE s.token_hash=? AND s.expires_at>? ON CONFLICT(session_token_hash) DO UPDATE SET expires_at=excluded.expires_at,created_at=excluded.created_at RETURNING session_token_hash,expires_at,created_at",
  insertRotatedAdminSession:"INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at,created_at,auth_version) SELECT ?,u.id,?,?,?,u.auth_version FROM sessions current JOIN users u ON u.id=current.user_id AND u.auth_version=current.auth_version AND u.suspended_at IS NULL JOIN admin_principal ap ON ap.user_id=u.id AND ap.slot='primary' WHERE current.token_hash=? AND current.expires_at>? AND u.id=? RETURNING token_hash,user_id,csrf_token,expires_at,created_at,auth_version",
  insertAdminAuditIfSession:"INSERT INTO admin_audit_events(id,actor_user_id,target_user_id,action,reason,result,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM sessions WHERE token_hash=?) RETURNING id",
  deleteRotatedAdminSession:"DELETE FROM sessions WHERE token_hash=? AND EXISTS(SELECT 1 FROM sessions WHERE token_hash=?) RETURNING token_hash",
  adminElevation:"SELECT session_token_hash,expires_at,created_at FROM admin_elevations WHERE session_token_hash=? AND expires_at>?",
  deleteExpiredAdminElevations:"DELETE FROM admin_elevations WHERE expires_at<=?",
  revokeUserSessionsUser:"UPDATE users SET auth_version=auth_version+1 WHERE id=? RETURNING id,name,email,created_at,email_verified_at,auth_version,suspended_at",
  revokeUserSessionsDelete:"DELETE FROM sessions WHERE user_id=? RETURNING token_hash",
  suspendUser:"UPDATE users SET suspended_at=?,auth_version=auth_version+1 WHERE id=? AND suspended_at IS NULL AND NOT EXISTS(SELECT 1 FROM admin_principal ap WHERE ap.user_id=users.id) RETURNING id,name,email,created_at,email_verified_at,auth_version,suspended_at",
  restoreUser:"UPDATE users SET suspended_at=NULL WHERE id=? AND suspended_at IS NOT NULL RETURNING id,name,email,created_at,email_verified_at,auth_version,suspended_at",
  insertAdminAudit:"INSERT INTO admin_audit_events(id,actor_user_id,target_user_id,action,reason,result,created_at) VALUES(?,?,?,?,?,?,?) RETURNING id",
  insertAdminAuditIfChanged:"INSERT INTO admin_audit_events(id,actor_user_id,target_user_id,action,reason,result,created_at) SELECT ?,?,?,?,?,?,? WHERE changes()>0 RETURNING id",
  adminAudit:"SELECT a.id,a.target_user_id,a.action,a.reason,a.result,a.created_at,actor.id AS actor_id,actor.name AS actor_name,actor.email AS actor_email,target.id AS target_id,target.name AS target_name,target.email AS target_email FROM admin_audit_events a JOIN users actor ON actor.id=a.actor_user_id LEFT JOIN users target ON target.id=a.target_user_id ORDER BY a.created_at DESC,a.id DESC LIMIT ?",
  insertSupportTicket:"INSERT INTO support_tickets(id,reference,user_id,name,email,category,subject,reference_id,message,status,admin_note,last_response_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'new',NULL,NULL,?,?) RETURNING id,reference,user_id,name,email,category,subject,reference_id,message,status,admin_note,last_response_at,created_at,updated_at",
  supportTicketById:"SELECT id,reference,user_id,name,email,category,subject,reference_id,message,status,admin_note,last_response_at,created_at,updated_at FROM support_tickets WHERE id=?",
  adminSupportTickets:"SELECT id,reference,user_id,name,email,category,subject,reference_id,message,status,admin_note,last_response_at,created_at,updated_at FROM support_tickets WHERE (?='' OR status=?) ORDER BY CASE status WHEN 'new' THEN 0 WHEN 'open' THEN 1 WHEN 'waiting' THEN 2 ELSE 3 END,updated_at DESC,id DESC LIMIT ? OFFSET ?",
  adminSupportCount:"SELECT COUNT(*) AS total FROM support_tickets WHERE (?='' OR status=?)",
  updateSupportTicket:"UPDATE support_tickets SET status=?,admin_note=?,last_response_at=CASE WHEN ?=1 THEN ? ELSE last_response_at END,updated_at=? WHERE id=? AND updated_at=? RETURNING id,reference,user_id,name,email,category,subject,reference_id,message,status,admin_note,last_response_at,created_at,updated_at",
  markSupportResponseSent:"UPDATE support_tickets SET last_response_at=?,updated_at=MAX(updated_at,?) WHERE id=? RETURNING id,reference,user_id,name,email,category,subject,reference_id,message,status,admin_note,last_response_at,created_at,updated_at",
  claimSupportRequestEvent:"INSERT INTO support_request_events(id,ip_hash,email_hash,created_at) SELECT ?,?,?,? WHERE (SELECT COUNT(*) FROM support_request_events WHERE ip_hash=? AND created_at>=?)<? AND (SELECT COUNT(*) FROM support_request_events WHERE email_hash=? AND created_at>=?)<? AND (SELECT COUNT(*) FROM support_request_events WHERE created_at>=?)<? RETURNING id",
  deleteOldSupportRequestEvents:"DELETE FROM support_request_events WHERE created_at<?"
};

module.exports = { SCHEMA,SQL };
